[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/"
]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config

